Return a [400] Bad Request if evaluating a non-existent kw
Instead of [500] Internal Server Error.

Example:

	# om testdrbd config eval --kw app#1.starte
	Error: testdrbd: [400] EvalAs: keyword does not exist: "app#1.starte"